# Generated by Django 5.0.7 on 2024-12-11 10:19

import django.core.validators
import django.db.models.deletion
import ganesh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credbasicdetailform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Dob', models.DateField(validators=[ganesh.models.validate_age])),
                ('phone_number', models.BigIntegerField()),
                ('pan_num', models.CharField(max_length=10, validators=[ganesh.models.validate_pan])),
                ('Aadhar_number', models.CharField(max_length=12)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('application_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('existing_creditcard_holder', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=10)),
                ('card_limit', models.IntegerField(blank=True, null=True, validators=[ganesh.models.validate_amount])),
                ('card_belonging_bank_name', models.CharField(blank=True, max_length=25, null=True, validators=[ganesh.models.validate_only_letters])),
                ('expiry_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='creCibilCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='', max_length=6)),
                ('cibil_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganesh.credbasicdetailform')),
            ],
        ),
        migrations.CreateModel(
            name='CreditDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[ganesh.models.validate_only_letters])),
                ('last_name', models.CharField(max_length=100, validators=[ganesh.models.validate_only_letters])),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], max_length=10)),
                ('father_name', models.CharField(max_length=100, validators=[ganesh.models.validate_only_letters])),
                ('date_of_birth', models.DateField(validators=[ganesh.models.validate_date])),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, validators=[ganesh.models.validate_mobile_number])),
                ('pan_card_number', models.CharField(blank=True, max_length=10, null=True, validators=[ganesh.models.validate_pan])),
                ('aadhar_card_number', models.CharField(max_length=12, validators=[ganesh.models.validate_aadhar_number])),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], max_length=10)),
                ('email', models.EmailField(max_length=254, validators=[ganesh.models.validate_email])),
                ('current_address', models.TextField(validators=[ganesh.models.validate_address])),
                ('current_address_type', models.TextField(choices=[('RENT', 'Rent'), ('OWN', 'Own')])),
                ('current_address_pincode', models.CharField(max_length=6, validators=[ganesh.models.validate_pincode])),
                ('aadhar_address_type', models.TextField(choices=[('RENT', 'Rent'), ('OWN', 'Own')])),
                ('aadhar_address', models.TextField(validators=[ganesh.models.validate_address])),
                ('aadhar_pincode', models.CharField(max_length=6, validators=[ganesh.models.validate_pincode])),
                ('running_emis', models.CharField(max_length=10, validators=[ganesh.models.validate_amount])),
                ('net_salary', models.CharField(max_length=10, validators=[ganesh.models.validate_amount])),
                ('company_name', models.CharField(max_length=100, validators=[ganesh.models.validate_only_letters])),
                ('company_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('GOVERNMENT', 'Government'), ('SELF_EMPLOYED', 'Self-employed'), ('OTHER', 'Other')], max_length=20)),
                ('job_joining_date', models.DateField()),
                ('job_location', models.CharField(max_length=100)),
                ('total_job_experience', models.IntegerField()),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, validators=[ganesh.models.validate_email])),
                ('office_address', models.TextField(blank=True, null=True, validators=[ganesh.models.validate_address])),
                ('office_address_pincode', models.CharField(max_length=6, validators=[ganesh.models.validate_pincode])),
                ('ref1_name', models.CharField(max_length=200, validators=[ganesh.models.validate_only_letters])),
                ('ref1_mobile', models.CharField(max_length=10, validators=[ganesh.models.validate_mobile_number])),
                ('ref2_name', models.CharField(blank=True, max_length=200, null=True, validators=[ganesh.models.validate_only_letters])),
                ('ref2_mobile', models.CharField(blank=True, max_length=10, null=True, validators=[ganesh.models.validate_mobile_number])),
                ('own_house', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('dsaref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('franrefCode', models.CharField(blank=True, max_length=100, null=True)),
                ('empref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('application_id', models.CharField(blank=True, max_length=200, null=True)),
                ('basicdetailform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ganesh.credbasicdetailform')),
            ],
        ),
        migrations.CreateModel(
            name='creditDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card_front', models.ImageField(upload_to='documents/', validators=[ganesh.models.validate_image_file])),
                ('aadhar_card_back', models.ImageField(upload_to='documents/', validators=[ganesh.models.validate_image_file])),
                ('pan_card', models.ImageField(upload_to='documents/', validators=[ganesh.models.validate_image_file])),
                ('customer_photo', models.ImageField(upload_to='documents/', validators=[ganesh.models.validate_image_file])),
                ('bank_statement', models.FileField(upload_to='documents/', validators=[ganesh.models.validate_pdf_file])),
                ('payslip_1', models.FileField(upload_to='documents/', validators=[ganesh.models.validate_pdf_file])),
                ('payslip_2', models.FileField(blank=True, null=True, upload_to='documents/', validators=[ganesh.models.validate_pdf_file])),
                ('payslip_3', models.FileField(blank=True, null=True, upload_to='documents/', validators=[ganesh.models.validate_pdf_file])),
                ('employee_id_card', models.ImageField(blank=True, null=True, upload_to='documents/', validators=[ganesh.models.validate_image_file])),
                ('current_address_proof', models.FileField(upload_to='documents/', validators=[ganesh.models.validate_image_file])),
                ('other_document_1', models.FileField(blank=True, null=True, upload_to='documents/', validators=[ganesh.models.validate_pdf_file])),
                ('other_document_2', models.FileField(blank=True, null=True, upload_to='documents/', validators=[ganesh.models.validate_pdf_file])),
                ('personal_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pldocument', to='ganesh.creditdetail')),
            ],
        ),
    ]
